version: '3'

services:
  api:
    build: .  # assumes your Dockerfile is in the same directory as docker-compose.yml
    ports:
      - "5000:5000"  # maps port 5000 inside the Docker container to port 5000 on your machine
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/todo_db
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: