name: Deploy to Okteto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Okteto
      run: |
          curl https://get.okteto.com -sSfL | sh

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Login to Okteto Cloud
      uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ns6jason/api_project:latest

    - name: Initialize Okteto Context
      run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
      
    - name: Deploy to Okteto
      run: |
        okteto deploy --build
